name: Bug report
description: Create a bug report to help us improve.
labels:
  - BUG
title: '[BUG]'
body:
  - type: checkboxes
    attributes:
      label: Make sure you have updated to the latest version of the module
      description: This may be a beta version of the module, or may require you to update your companion.
      options:
        - label: I have checked this on the latest version of the module
          required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Screenshots are always helpful to understand the problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment (please complete the following information)
      description: |
        examples:
          - **OS**: Windows 10
          - **Browser**: Chrome 94
          - **Companion Version**: 2.2.0-b177f8fb-3722
          - **Module Version**: 1.0.0
          - **Device Firmware/Software Version (If applicable)**: 3.0.6
          - **Device Model (If applicable)**: My Device PRO
      value: |
        - OS:
        - Browser:
        - Companion Version:
        - Module Version:
        - Device Firmware/Software Version (If applicable):
        - Device Model (If applicable):
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
